language: node_js
node_js:
  - 8
  - 10
  - 12
before_install: dpkg --compare-versions `npm -v` ge 6 || npm i -g npm@^6
deploy:
  - provider: script
    script: npx nlm release
    skip_cleanup: true
    'on':
      branch: master
      node: 12
